apiVersion: v1
data:
  WebHookSecretKey: YmYwNGFlYjQ5MTRmNGU2NA==
  username: hidden-username
  .dockercfg: hidden-docker
  password: hidden-password
kind: Secret
metadata:
  name: a-simple-app-github-webhook-secret
  namespace: n1
type: Opaque
