apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: haproxy-service
    app.kubernetes.io/instance: gitops
  name: fe
  namespace: n1
spec:
  host: fe-n1.apps-crc.testing
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: haproxy-service
    weight: 100
  wildcardPolicy: None
