apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: simple-app
    app.kubernetes.io/component: simple-app
    app.kubernetes.io/instance: simple-app
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
  name: simple-app
  namespace: n1
spec:
  host: simple-app-n1.apps-crc.testing
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: simple-app
    weight: 100
  wildcardPolicy: None
