apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
  labels:
    app: export-app
    app.kubernetes.io/instance: round-trip
    pod-template-hash: 8f946d798
  name: export-app-deploy-8f946d798
  namespace: n1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: export-app
      pod-template-hash: 8f946d798
  template:
    metadata:
      labels:
        app: export-app
        pod-template-hash: 8f946d798
    spec:
      containers:
        - env:
            - name: MY_GITHUB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: github-basic-auth
            - name: MY_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: password
                  name: github-basic-auth
          image: jduimovich/export-app
          imagePullPolicy: Always
          name: export-app-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-101-role
      serviceAccountName: k8s-101-role
      terminationGracePeriodSeconds: 30
