apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/fib-go-deploy: runtime/default
    deployment.kubernetes.io/desired-replicas: "4"
    deployment.kubernetes.io/max-replicas: "5"
  labels:
    app: fib
    pod-template-hash: 7b9869cd7b
  name: fib-go-deploy-7b9869cd7b
  namespace: n1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fib
      pod-template-hash: 7b9869cd7b
  template:
    metadata:
      labels:
        app: fib
        pod-template-hash: 7b9869cd7b
    spec:
      containers:
        - image: docker.io/jduimovich/fib-go:4e7342d
          imagePullPolicy: Always
          name: fib-go-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 48Mi
            requests:
              cpu: 100m
              memory: 32Mi
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
