apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/fib-quarkus-deploy: runtime/default
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
  labels:
    app: fib
    pod-template-hash: 65756b4c65
  name: fib-quarkus-deploy-65756b4c65
  namespace: n1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fib
      pod-template-hash: 65756b4c65
  template:
    metadata:
      labels:
        app: fib
        pod-template-hash: 65756b4c65
    spec:
      containers:
        - image: jduimovich/fib-quarkus:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /fib
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: fib-quarkus-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 384Mi
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
