apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/fib-node-deploy: runtime/default
    deployment.kubernetes.io/desired-replicas: "2"
    deployment.kubernetes.io/max-replicas: "3"
  labels:
    app: fib
    pod-template-hash: 6979f4867b
  name: fib-node-deploy-6979f4867b
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fib
      pod-template-hash: 6979f4867b
  template:
    metadata:
      labels:
        app: fib
        pod-template-hash: 6979f4867b
    spec:
      containers:
        - image: docker.io/jduimovich/fib-node:8e35314
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: fib-node-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 32Mi
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
