apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/frontend-deploy: runtime/default
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
  labels:
    app: frontend
    pod-template-hash: 65cf895b58
  name: frontend-deploy-65cf895b58
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      pod-template-hash: 65cf895b58
  template:
    metadata:
      labels:
        app: frontend
        pod-template-hash: 65cf895b58
    spec:
      containers:
        - image: docker.io/jduimovich/frontend:a3b1777
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: frontend-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 48Mi
            requests:
              cpu: 100m
              memory: 48Mi
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
