apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIDbvRdnw+jmYwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTYyMzMwNjUxODAe
    Fw0yMTA2MTAwNjI4MzdaFw0yMzA4MDkwNjI4MzhaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE2MjMzMDY1MTgwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6DYEbeXO2+3B1NLNQgqtqu0WqC2R+iexC
    VghbX0j+LEbvYzPl84YxA+UTVQ2Vf5vGqOEG+Ap58ZOduYQPb8Zis7OacC8MOjXj
    zYs2gUoMSCcdAxGujPkMSESeHA+bt1B3/9AhUZrhqvx+9VMGgjdKg7Jas306ViVu
    wn1kWfqZCU/aneunDcUOomlIeiNFecTTWw0n9tRHJebvGAwVltNsXJLUd+LUq2js
    /0to+B1Mr1HDViaju9Y3qp45bUANKcDD+RhSekL6YQrcjEKSPo60jjZilLeGkYdc
    Jkirk7UdcixrR6iBHC017JhQTyr3W2CEX6Ov1d6v+efk3rJKNbSlAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQEIbUs
    XMLCEGhjRn/grFHTTIcaRjAfBgNVHSMEGDAWgBQEIbUsXMLCEGhjRn/grFHTTIca
    RjANBgkqhkiG9w0BAQsFAAOCAQEAYYC6o4ETq2TUVD/u+B/IGmWwO0kmcMI4fmwK
    +IOF7pBRMVxaW+vuGWM4Db/2dRvFY/jvLXaJ5lQOPOAiQhOGuQvzDq+x/A76+nF9
    /5WdmYUE8pBsZ8yeZYcew0opT67bkScqscQZ7J02LRYnjHWv9g8nSfSW6TtlpbI2
    gbuJQHxVy29LvT2zQkwW+kDZQ+VNQUdP0Y1d9aCXm1evaW897xUwqJ5vUEjkXxrn
    L/L6aRc7aQTVD2ena+mseRQ4322ZfY8HXzSAfqhDhROSVCHWdUBfVBEy8McECVOE
    WLVmeTRKK2h4PszBLPr56Y0nQ8LfTJns+4IY2g2JAJjIj0plkg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-service-cabundle
  namespace: n1
