apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIFD5B6e7Pj8MwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTYyMTQ4NjIyMTAe
    Fw0yMTA1MjAwNDUwMjFaFw0yMzA3MTkwNDUwMjJaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE2MjE0ODYyMjEwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5+VX6akIPl1CCXh34qMygZ7BmQtFmxv9h
    8lXZGhhlJgKvFnTIGmA/f0LG10rquf/sqRqxoAYbWuBlt2NzNQhzPFrVIeKWkewA
    M2HCgoSm5sYk6moUQedtA241oAX8u2Nqijm+k/mj8EUQGo440+sli3o13w4TJ7PC
    BJGAYdd1avT4IE1WX1PFLmtWV97XsDcvrWtC+g40C0Oe+zWlagl6stSHU6umByZl
    qlkeUDqB3VImAMrYYJV/vibgLUOnZIZXinxUj3uROa9khm2IZGx55k/sUQGUM0By
    ptf9W98VQ9wUK83RO0EgfcIWNfCQkNHEUKGcPdghUvA94kF6morxAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT9+eXy
    p8DudrknAvM1/9GSCvFGxTAfBgNVHSMEGDAWgBT9+eXyp8DudrknAvM1/9GSCvFG
    xTANBgkqhkiG9w0BAQsFAAOCAQEAHdpQzU15EPzyZA620pu6CHrLRLe61ULOIrZW
    sFDkeL6lUKMY87Q1THOVxMmw2HAWy1/9WR9Gfa3sojKNmq8o6nk90cVMtnakZYy/
    4SmVmTogzxrPKmC9EarG9DgpNyy8CsQoGuzORypQiJlOnx/0JZgmxanhQW9pDQnQ
    so76gsxkFxlJtmXg7CjHEpPGYycIRlLYOhMv0LhlVN2cHyLgTqDNQvEa9XAhkcN4
    zHxiXfDL3tclOifuq1cnJhKMrsOwWhMM6SSIVDHpUBUBHHgJH5uQNobO9LdTQn85
    dgv2W7HqM2GJeapDtpktTlu5ZTRUACgkC9PWoP2qrodFuVCxuQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/instance: round-trip
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-service-cabundle
  namespace: n1
