apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/jduimovich/a-simple-app
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"a-simple-app:latest","namespace":"n1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"a-simple-app\")].image","pause":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: a-simple-app
    app.kubernetes.io/component: a-simple-app
    app.kubernetes.io/instance: a-simple-app
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
  name: a-simple-app
  namespace: n1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-simple-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: a-simple-app
        deploymentconfig: a-simple-app
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/n1/a-simple-app@sha256:a28a3ff07799c370cdfe38c6e33e4bd8753034b911c57adaa13fa577a0314a90
          imagePullPolicy: Always
          name: a-simple-app
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
