apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: export-app
  name: export-app-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: export-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: export-app
    spec:
      containers:
        - env:
            - name: MY_GITHUB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: github-basic-auth
            - name: MY_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: password
                  name: github-basic-auth
          image: localhost:5000/export-app
          imagePullPolicy: Always
          name: export-app-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
