apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: export-app
    app.kubernetes.io/instance: round-trip
  name: export-app-deploy
  namespace: n1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: export-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: export-app
    spec:
      containers:
        - env:
            - name: MY_GITHUB_REPO
              valueFrom:
                configMapKeyRef:
                  key: repo
                  name: git-user-and-email
            - name: MY_GITHUB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: git-user-and-email
            - name: MY_GITHUB_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: email
                  name: git-user-and-email
            - name: MY_GITHUB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: github-basic-auth
            - name: MY_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: password
                  name: github-basic-auth
          image: jduimovich/export-app
          imagePullPolicy: Always
          name: export-app-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-101-role
      serviceAccountName: k8s-101-role
      terminationGracePeriodSeconds: 30
