apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: gitops
  name: export-app-service
  namespace: n1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: export-app
  sessionAffinity: None
  type: ClusterIP
