apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: fibs-service
  namespace: n1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fib
  sessionAffinity: None
  type: ClusterIP
