apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: '["nginx-html-server","fib-service-in-go","fib-service-in-quarkus","fib-service-in-node"]'
  labels:
    app.kubernetes.io/instance: gitops
  name: fibs-service
  namespace: n1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fib
  sessionAffinity: None
  type: ClusterIP
