apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"fib-go-deploy"}]'
  labels:
    app: haproxy-service
    app.kubernetes.io/instance: gitops
  name: haproxy-service
  namespace: n1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: haproxy
  sessionAffinity: None
  type: ClusterIP
