apiVersion: build.openshift.io/v1
kind: Build
metadata:
  annotations:
    openshift.io/build-config.name: simple-app
    openshift.io/build.number: "1"
    openshift.io/build.pod-name: simple-app-1-build
  labels:
    app: simple-app
    app.kubernetes.io/component: simple-app
    app.kubernetes.io/instance: simple-app
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
    buildconfig: simple-app
    openshift.io/build-config.name: simple-app
    openshift.io/build.start-policy: Serial
  name: simple-app-1
  namespace: n1
spec:
  nodeSelector: null
  output:
    pushSecret:
      name: builder-dockercfg-rhh78
    to:
      kind: ImageStreamTag
      name: simple-app:latest
  postCommit: {}
  resources: {}
  revision:
    git:
      author:
        email: jduimovich@gmail.com
        name: John Duimovich
      commit: 97fbe707f99a91532ab08ee6d2118f3bdf44a375
      committer:
        email: jduimovich@gmail.com
        name: John Duimovich
      message: ubuntu-20.04 buildah test
    type: Git
  serviceAccount: builder
  source:
    contextDir: /
    git:
      uri: https://github.com/jduimovich/simple-app
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:88c99371d8aa44e98b504f62ba30f738a8db2eff918a05d3b6e7bfb9ba0a15d2
      pullSecret:
        name: builder-dockercfg-rhh78
    type: Source
  triggeredBy:
    - imageChangeBuild:
        fromRef:
          kind: ImageStreamTag
          name: nodejs:14-ubi7
          namespace: openshift
        imageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:88c99371d8aa44e98b504f62ba30f738a8db2eff918a05d3b6e7bfb9ba0a15d2
      message: Image change
