apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    export.app.control/prune: "true"
  name: export-app-sa
  namespace: n1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: export-app-sa
subjects:
  - kind: ServiceAccount
    name: export-app-sa
    namespace: n1
